### ISSUE TITLE
schema in js方案

### ISSUE THREAD

**Issue by yanghuabei** [yanghuabei/simple-json-schema#1]
# 问题
- 使用json书写json schema不方便
- json schema嵌套层次深

[json schema关键词](http://agroup.baidu.com/work/md/article/151862)
[json schema示例](http://agroup.baidu.com/work/md/article/151861)
[json schema介绍](https://spacetelescope.github.io/understanding-json-schema/index.html)
# 目标
- 简化json schema的书写
# 方案

使用js书写schema，将json schema的关键词使用js的功能实现，充分利用js的功能简化schema的书写。

参考React.propTypes, tcomb使用js表达变量的类型、结构、约束。
## 方案1

以简洁的函数链式调用的方式书写schema。
### 基本类型

提供5中基本类型`Str`、`Int`、`Num`、`Arr`、`Obj`，通过模块ET使用。

```
export default {
    get str() {
        return new Str();
    }
    get Int() {
        return new Int();
    }
    // 其他类型...
}

// 使用
import ET from 'ecom-type';

let schema = {
    name: ET.str  
};
```
### 约束字段

每种类型对应的校验关键词作为该类型的方法。
#### Str
- `pattern(regex)`: 规则；
- `size(max, min)`: 长度限制；
- `maxLength(int)`: 长度上限；
- `minLength(int)`: 长度下限；

```
ET.str.pattern(/xxx.*/);

// 等同于ET.str.maxLength(10).minLength(1)
ET.str.size(10, 1);

// 等同于ET.str.minLength(1)
ET.str.size(null, 1);
```
#### Num & Int
- `range(max, exclusiveMaximum, min, exclusiveMinmum)`：数值上下边界；
- `maximum(num)`: 数值上限；
- `exclusiveMaximum()`：上限不包含maximum；
- `minimum(num)`: 数值下限；
- `exclusiveMinimum()`：下限不包含minimum；
- `multipleOf(num)`：数值倍数

```
// 等同于ET.num.maximum(100).exclusizeMaximum().minimum(10).exclusizeMinimum()
ET.num.range(100, true, 10, true);
ET.num.range(100, 10);
ET.num.range(null, 10);
ET.num.range(100);

ET.num.multipleOf(3);
```
#### Arr
- `size(max, min)`: 数组长度限制；
- `maxLength(int)`: 长度上限；
- `minLength(int)`: 长度下限;
- `items(Schema | Array.<Schema>)`：数组项schema
- `extraItems(bool | Schema)`：alias for `additionalItems`
- `uniq()`: 不允许重复，alias for `uniqueItems`

```
ET.arr.size(10).uniq().items(ET.int).extraItems(false);
```
#### Obj
- `size(max, min)`: 属性数目；
- `maxProperties(int)`: 属性数目上限；
- `minProperties(int)`：属性数目下限；
- `props()`：属性schema，alias for `properties`；
- `extraProps()`：是否允许其他属性，或者其他属性的schema，alias for `additionalProperties`

```
ET.obj.size(20, 2).props({
    key1: ET.str,
    key2: ET.int
});
```
#### 通用约束
- `mayBe()`: 非必需，字段默认为`required`；
- `enum(a, b, ...)`: 枚举值；
- `allOf(schema1, schema2, ...)`
- `oneOf(schema1, schema2, ...)`
- `anyOf(schema1, schema2, ...)`
- `not(schema)`

```
ET.str.mayBe();

ET.enum(1, 2);

ET.allOf(schema1, schema2);

ET.not(schema).mayBe();
```
#### format
- date, date-time, uri, email

```
ET.format.date();
```
### 示例

```
// schema in js
let schema = {
    name: ET.str.size(100, 10).pattern(/xxxx.*/),
    gender: ET.enum('男', '女').mayBe(),
    foo: ET.obj.props({
        key1: ET.str.size(null, 1),
        key2: ET.arr.items(ET.int.range(10))
    }),
    bar: ET.allOf(ET.str, ET.num).mayBe(),
    birthday: ET.format.date().mayBe()
};
```

```
// in json schema
{
    "id": "",
    "title": "",
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "maxLength": 1000,
            "minLength": 10,
            "pattern": /xxx.*/
        },
        "gender": {
            "enum": ['男', '女']
        },
        "foo": {
            "type": "object",
            "properties": {
                "key1": {
                    "type": "string",
                    "minLength": 1
                },
                "key2": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "max": 20
                    }
                }
            }
        },
        "bar": {
            "allOf": [
                {"type": "string"},
                {"type": "number"}
            ]
        },
        "birthday": {"format": "date"}
    },
    "required": ["name", "foo"]
}
```
## 方案2

通过函数传递约束参数书写schema。
- 定义`Str`, `Int`, `Num`, `Arr`, `Obj`类对应json schema中的`type`的取值；

```
let schema = {
    name: Str(),
    foo: Obj()
};
```
- 约束字段作为参数传给上述类；

```
let schema = {
    name: Str({
        maxLength: 100,
        minLength: 10,
        pattern: /xxxx.*/,
        required: true
    }),
    foo: Obj({
        properties: {
            key1: Str({minLength: 1}),
            key2: Arr({items: Int({max: 10})})
        }
    })
};

```
- 定义`enum`, `allOf`, `oneOf`, `not`, `anyOf`函数，返回值为schema，对应json schema中关键字；

```
let schema = {
    gender: enum('男', '女'),
    bar: allOf(Str(), Num(), enum(1, 2))
};
```
- 定义`format`对象，支持json schema提供的format，开放自定义`format`

```
let schema = {
    birthday: format.date(),
    blog: format.uri()
};
```
#### js schema

```
let schema = {
    name: Str({
        maxLength: 100,
        minLength: 10,
        pattern: /xxxx.*/,
        required: true
    }),
    gender: enum('男', '女'),
    foo: Obj({
        properties: {
            key1: Str({minLength: 1}),
            key2: Arr({items: Int({max: 10})})
        }
    }),
    bar: allOf(Str(), Num()),
    birthday: format.date()
};
```
#### json schema

```
{
    "id": "",
    "title": "",
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "maxLength": 1000,
            "minLength": 10,
            "pattern": /xxx.*/
        },
        "gender": {
            "enum": ['男', '女']
        },
        "foo": {
            "type": "object",
            "properties": {
                "key1": {
                    "type": "string",
                    "minLength": 1
                },
                "key2": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "max": 20
                    }
                }
            }
        },
        "bar": {
            "allOf": [
                {"type": "string"},
                {"type": "number"}
            ]
        },
        "birthday": {"format": "date"}
    },
    "required": ["name"]
}
```
#### 优点
- 非常简洁
- schema定义可通过多种方式复用：模块机制、变量等
#### 缺点
- 简写、合并json schema的验证规则字段名，增大了理解难度；
- 验证规则的添加通过函数调用实现，不够直观；参数过多、过长时阅读难度变大；
- ~~缺少schema正确性验证工具~~
#### 优点
- 验证规则通过普通对象定义，直观；
- 规则字段名跟json schema一致；
- schema定义可通过多种方式复用：模块机制、变量等
#### 缺点
- 不如方案1简洁
- ~~缺少schema正确性验证工具~~

**Comment by yanghuabei** [comment]
@otakustay

> 我觉得基于方案1，我们没必要强制要求合并规则字段名，比如 str.size(100, true, 0, true) 完全也可以写成 str.maxLength(100, true).minLength(0, true) 或者 str.maxLengthInclusive(100).minLengthInclusive(0) 把这些都提供出来，让使用者自己做选择就好

这个可以的。

> 如果我们知道一个模块的export是一个json schema，那么无论它是什么格式，我们应该都可以针对export来做正确性验证 虽然不能像source map一样从错误找回根源，但是大部分情况下json schema只要知道最终的错误都是能快速定位的

好的，我改一下内容，这个验证貌似更好做了，直接在各种类型Schema类上实现就可以了

**Comment by otakustay** [comment]
总的来说我比较倾向方案1

**Comment by Exodia** [comment]
倾向方案1

**Comment by yanghuabei** [comment]
好，我也觉得1比较合适，接下来我根据方案1做设计

**Comment by yanghuabei** [comment]
@otakustay @Exodia 

实现在这里，还缺少几个关键词的实现，另外还需要提供扩展的api。

https://github.com/yanghuabei/schema-in-js
